# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - ci_cd
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.CD_CI }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
          
      - name: Adding Known Hosts
        run: ssh-keyscan -H strolr3.railwaynet.datasages.com >> ~/.ssh/known_hosts
        
      - name: Check ssh connect
        run: ssh ec2-user@strolr3.railwaynet.datasages.com ls -la
      
      - uses: actions/checkout@v2
      - name: Set up JDK 8.0.242
        uses: actions/setup-java@v1
        with:
          java-version: 8.0.242
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          
      - name: Check Java version
        run: java -version

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Copy artifacts
        run: scp target/*.jar src/main/resources/start.sh ec2-user@strolr3.railwaynet.datasages.com:~/strolr/

      - name: Run application
        run: ssh ec2-user@strolr3.railwaynet.datasages.com 'cd /home/ec2-user/strolr ; bash start.sh < /dev/null > /tmp/log.txt 2>&1 &'
